# Site settings
title: Dan Koopman
header-img: img/home-bg.jpg
email: info@conviveo.co.uk
copyright_name: Conviveo Ltd
description: "Continuous Improvements, Cloud, Costs and General Technology"
baseurl: ""
url: "http://www.conviveo.co.uk"
twitter_username: Conviveo
github_username:  conviveo
# facebook_username:  IronSummitMedia
email_username:  info@conviveo.co.uk

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
